name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shadcn_ui:
    path: ..
  flutter_solidart: ^2.1.0
  awesome_flutter_extensions: ^2.0.1
  collection: ^1.18.0
  get: ^4.6.6
  boxy: ^2.2.1
  disco: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: UbuntuMono
      fonts:
        - asset: fonts/UbuntuMono-Regular.ttf
        - asset: fonts/UbuntuMono-Bold.ttf
          weight: 700
  assets:
    - assets/
