name: shadcn_ui
description: shadcn-ui ported in Flutter. Awesome UI components for Flutter, fully customizable.
version: 0.0.0
homepage: https://mariuti.com/shadcn-ui
repository: https://github.com/nank1ro/shadcn-ui
documentation: https://mariuti.com/shadcn-ui
topics:
  - ui

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.0
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_svg: ^2.0.9
  rive: ^0.12.4
  vector_graphics: ^1.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
