name: shadcn_ui
description: shadcn-ui ported in Flutter. Awesome UI components for Flutter, fully customizable.
version: 0.5.5
homepage: https://mariuti.com/shadcn-ui
repository: https://github.com/nank1ro/flutter-shadcn-ui
documentation: https://mariuti.com/shadcn-ui
topics:
  - ui

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  lucide_icons_flutter: ^1.1.0
  # used by Table
  two_dimensional_scrollables: ^0.3.1
  vector_graphics: ^1.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  fonts:
    - family: Geist
      fonts:
        - asset: fonts/Geist-Thin.otf
          weight: 100
        - asset: fonts/Geist-UltraLight.otf
          weight: 200
        - asset: fonts/Geist-Light.otf
          weight: 300
        - asset: fonts/Geist-Regular.otf
          weight: 400
        - asset: fonts/Geist-Medium.otf
          weight: 500
        - asset: fonts/Geist-SemiBold.otf
          weight: 600
        - asset: fonts/Geist-Bold.otf
          weight: 700
        - asset: fonts/Geist-Black.otf
          weight: 800
        - asset: fonts/Geist-UltraBlack.otf
          weight: 900
