name: shadcn_ui
description: shadcn-ui ported in Flutter. Awesome UI components for Flutter, fully customizable.
version: 0.17.1
homepage: https://flutter-shadcn-ui.mariuti.com
repository: https://github.com/nank1ro/flutter-shadcn-ui
documentation: https://flutter-shadcn-ui.mariuti.com
topics:
  - user-interface
  - design-system
  - shadcn-ui
  - material-alternative

environment:
  sdk: ^3.0.0
  flutter: ">=3.27.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.14
  intl: ^0.19.0
  lucide_icons_flutter: ^1.1.0
  # used by Table
  two_dimensional_scrollables: ^0.3.1
  vector_graphics: ^1.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  fonts:
    - family: Geist
      fonts:
        - asset: fonts/Geist-Thin.otf
          weight: 100
        - asset: fonts/Geist-UltraLight.otf
          weight: 200
        - asset: fonts/Geist-Light.otf
          weight: 300
        - asset: fonts/Geist-Regular.otf
          weight: 400
        - asset: fonts/Geist-Medium.otf
          weight: 500
        - asset: fonts/Geist-SemiBold.otf
          weight: 600
        - asset: fonts/Geist-Bold.otf
          weight: 700
        - asset: fonts/Geist-Black.otf
          weight: 800
        - asset: fonts/Geist-UltraBlack.otf
          weight: 900
    - family: GeistMono
      fonts:
        - asset: fonts/GeistMono-Thin.otf
          weight: 100
        - asset: fonts/GeistMono-UltraLight.otf
          weight: 200
        - asset: fonts/GeistMono-Light.otf
          weight: 300
        - asset: fonts/GeistMono-Regular.otf
          weight: 400
        - asset: fonts/GeistMono-Medium.otf
          weight: 500
        - asset: fonts/GeistMono-SemiBold.otf
          weight: 600
        - asset: fonts/GeistMono-Bold.otf
          weight: 700
        - asset: fonts/GeistMono-Black.otf
          weight: 800
        - asset: fonts/GeistMono-UltraBlack.otf
          weight: 900
