name: shadcn_ui
description: shadcn/ui ported in Flutter. Awesome UI components for Flutter, fully customizable.
version: 0.43.4
homepage: https://flutter-shadcn-ui.mariuti.com
repository: https://github.com/nank1ro/flutter-shadcn-ui
documentation: https://flutter-shadcn-ui.mariuti.com
topics:
  - user-interface
  - design-system
  - shadcn-ui
  - material-alternative

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  boxy: ">=2.1.2 <3.0.0"
  collection: ">=1.0.0 <2.0.0"
  flutter:
    sdk: flutter
  flutter_animate: ">=4.4.0 <5.0.0"
  flutter_localizations:
    sdk: flutter
  flutter_svg: ">=2.0.0 <3.0.0"
  google_fonts: ^7.1.0
  intl: ">=0.19.0 <1.0.0"
  lucide_icons_flutter: ">=3.0.0 <4.0.0"
  # used by Table
  theme_extensions_builder_annotation: ^7.1.0
  two_dimensional_scrollables: ">=0.2.1 <1.0.0"
  universal_image: ">=1.0.3 <2.0.0"
  vector_graphics: ">=1.0.0 <2.0.0"

dev_dependencies:
  build_runner: ^2.10.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  theme_extensions_builder: ^7.1.0
  very_good_analysis: ^10.0.0

flutter: 
  uses-material-design: true
